# @see https://www.electron.build/configuration/configuration
{
  "$schema": "https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json",
  "appId": "gpq-image-ocr-gui",
  "asar": true,
  "productName": "GPQ Image OCR GUI",
  "directories": { "output": "release" },
  "files": ["dist", "dist-electron"],
  "extraFiles": ["gpq"],
  "mac":
    {
      "target": ["dmg"],
      "artifactName": "${productName}-Mac-${version}-Installer.${ext}",
    },
  "win":
    {
      "publish": ["github"],
      "target": [{ "target": "nsis", "arch": ["x64"] }],
      "artifactName": "${productName}-Windows-${version}-Setup.${ext}",
    },
  "nsis":
    {
      "oneClick": false,
      "perMachine": false,
      "allowToChangeInstallationDirectory": true,
      "deleteAppDataOnUninstall": false,
    },
  "linux":
    {
      "target": ["AppImage"],
      "artifactName": "${productName}-Linux-${version}.${ext}",
    },
}
