name: Publish GPQ Image OCR GUI

on:
  push:
    branches: ["master"]

permissions:
  contents: write

env:
  GPQ_CLI_VERSION: nightly-6fb97dc1de794ca8689068ee83c11f2c4087f319
  NODE_VERSION: "20"

jobs:
  check-gpq-cli:
    outputs:
      cache-hit: ${{ steps.check-gpq-cli-build.outputs.cache-hit }}
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      - name: Check gpq cli build
        id: check-gpq-cli-build
        uses: actions/cache@v4
        with:
          lookup-only: true
          key: ${{ runner.os }}-gpq-cli-${{ env.GPQ_CLI_VERSION }}
          path: ./gpq

  build-gpq-cli:
    if: needs.check-gpq-cli.outputs.cache-hit == false
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    needs: check-gpq-cli

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "SLAzurin/gpq-image-ocr"
          ref: "${{ env.GPQ_CLI_VERSION }}"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate py312 with black
        run: |
          black --target-version=py312 ./gpq.py
      - name: Build app
        run: |
          pyinstaller gpq.py
          Move-Item dist/gpq .
      - name: Cache gpq cli
        uses: actions/cache/save@v4
        with:
          enableCrossOsArchive: true
          path: ./gpq
          key: ${{ runner.os }}-gpq-cli-${{ env.GPQ_CLI_VERSION }}

  build-gpq-ui:
    needs:
      - build-gpq-cli
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache gpq cli
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          fail-on-cache-miss: true
          path: ./gpq
          key: ${{ runner.os }}-gpq-cli-${{ env.GPQ_CLI_VERSION }}
      - name: Verify gpq cli
        run: if (![System.IO.File]::Exists('gpq/gpq.exe')) { exit 1; }
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install dependencies
        run: |
          pnpm i
      - name: Build
        run: |
          pnpm run build
      - name: Write Release Body
        run: iex "echo `"${{ github.event.head_commit.message }}`" | Tee-Object RELEASE_BODY"
      - name: Release
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v1
        with:
          name: Release gpq-image-ocr-gui nightly-${{ github.sha }}
          body_path: ./RELEASE_BODY
          draft: false
          tag_name: nightly-${{ github.sha }}
          files: |
            latest.yml
            GPQ Image OCR GUI-Windows-*-Setup.exe.blockmap
            GPQ Image OCR GUI-Windows-*-Setup.exe
          fail_on_unmatched_files: true
